category = {
    'Knowledge': [
        'Space',
        'Philosophy',
        'Biology',
        'The future',
        'Physics',
        'Psychology',
        'Education',
        'History',
        'Math',
        'Science',
        'Covid-19'
    ],
    'Tech': [
        'Product',
        'Startups',
        'Marketing',
        'AI',
        'SaaS',
        'Engineering',
        'Crypto',
        'DTC',
        'Angel Investing',
        'Venture Capital',
        'VR/AR'
    ],
    'Language': [
        'Russian',
        'Hindi',
        'French',
        'Arabic',
        'Portuguese',
        'Japanese',
        'German',
        'Spanish',
        'Mandarin',
        'Indonesian'
    ],
    'Life': [
        'Weddings',
        'Traveling',
        'Pregnancy',
        'Grownuping',
        'Relationships',
        'Parenting',
        'Dating',
        'Support'
    ],
    'Wellness': [
        'Veganism',
        'Health',
        'Meditation',
        'Outdoors',
        'Nutrition',
        'Psychedelics',
        'Mindfulness',
        'Medicine',
        'Fitness',
        'Weights'
    ],
    'Hanging out': [
        '¯\*(ツ)*/¯',
        'Chill vibes',
        'Coworking',
        'Late night',
        'Meet people',
        'Bring a Drink',
        'Welcome Newbies',
        'PTR'
    ],
    'Identity': [
        'Millenials',
        'Latino',
        'Women',
        'BIPOC',
        'Black',
        'Disabled',
        'Gen Z',
        'LGBTQ',
        'Baby boomers',
        'Gen X',
        'South Asian',
        'East Asian',
        'Indiegenous'
    ],
    'Entertainment': [
        'Podcasts',
        'Perfomances',
        'Music',
        'Storytelling',
        'Gaming',
        'Comedy',
        'Television',
        'Karaoke',
        'Trivia',
        'Advice',
        'Variety',
        'Fun',
        'Movies',
        'Celebrities',
        'Anime & Manga'
    ],
    'Sports': [
        'Golf',
        'Soccer',
        'Cycling',
        'MMA',
        'Cricket',
        'Tennis',
        'Formula 1',
        'BasketBall',
        'baseball',
        'football'
    ],
    'Arts': [
        'Photography',
        'Beauty',
        'Architecture',
        'Writing',
        'Books',
        'Art',
        'Advertising',
        'Food & drink',
        'Sci-Fi',
        'Design',
        'Dance',
        'Theater'
    ],
    'Hustle': [
        'Entrepreneurship',
        'Real Estate',
        'Instagram',
        'Networking',
        'Small business',
        'Pitch practive',
        'Stocks',
        'Clubhouse',
        'TikTok'
    ],
    'World affairs': [
        'current events',
        'Social issues',
        'Geopolitics',
        'Economics',
        'U.S. Politics',
        'Markets',
        'Climate'
    ],
    'Faith': [
        'Sikhism',
        'Spirituality',
        'Islam',
        'Atheism',
        'Chiristianity',
        'Agnosticism',
        'Judaism',
        'Taoism',
        'Hinduism',
        'Buddhism',
    ]
}
