categories = [
    {'Knowledge': [
        'Space',
        'Philosophy',
        'Biology',
        'The future',
        'Physics',
        'Psychology',
        'Education',
        'History',
        'Math',
        'Science',
        'Covid-19'
    ]},
    {'Tech': [
        'Product',
        'Startups',
        'Marketing',
        'AI',
        'SaaS',
        'Engineering',
        'Crypto',
        'DTC',
        'Angel Investing',
        'Venture Capital',
        'VR/AR'
    ]},
    {'Language': [
        'Russian',
        'Hindi',
        'French',
        'Arabic',
        'Portuguese',
        'Japanese',
        'German',
        'Spanish',
        'Mandarin',
        'Indonesian'
    ]},
    {'Life': [
        'Weddings',
        'Traveling',
        'Pregnancy',
        'Grownuping',
        'Relationships',
        'Parenting',
        'Dating',
        'Support'
    ]},
    {'Wellness': [
        'Veganism',
        'Health',
        'Meditation',
        'Outdoors',
        'Nutrition',
        'Psychedelics',
        'Mindfulness',
        'Medicine',
        'Fitness',
        'Weights'
    ]},
    {'Hanging out': [
        '¯\*(ツ)*/¯',
        'Chill vibes',
        'Coworking',
        'Late night',
        'Meet people',
        'Bring a Drink',
        'Welcome Newbies',
        'PTR'
    ]},
    {'Identity': [
        'Millenials',
        'Latino',
        'Women',
        'BIPOC',
        'Black',
        'Disabled',
        'Gen Z',
        'LGBTQ',
        'Baby boomers',
        'Gen X',
        'South Asian',
        'East Asian',
        'Indigenous'
    ]},
    {'Entertainment': [
        'Podcasts',
        'Perfomances',
        'Music',
        'Storytelling',
        'Gaming',
        'Comedy',
        'Television',
        'Karaoke',
        'Trivia',
        'Advice',
        'Variety',
        'Fun',
        'Movies',
        'Celebrities',
        'Anime & Manga'
    ]},
    {'Sports': [
        'Golf',
        'Soccer',
        'Cycling',
        'MMA',
        'Cricket',
        'Tennis',
        'Formula 1',
        'BasketBall',
        'baseball',
        'football'
    ]},
    {'Arts': [
        'Photography',
        'Beauty',
        'Architecture',
        'Writing',
        'Books',
        'Art',
        'Advertising',
        'Food & drink',
        'Sci-Fi',
        'Design',
        'Dance',
        'Theater'
    ]},
    {'Hustle': [
        'Entrepreneurship',
        'Real Estate',
        'Instagram',
        'Networking',
        'Small business',
        'Pitch practive',
        'Stocks',
        'Clubhouse',
        'TikTok'
    ]},
    {'World affairs': [
        'Current events',
        'Social issues',
        'Geopolitics',
        'Economics',
        'Politics',
        'Markets',
        'Climate'
    ]},
    {'Faith': [
        'Sikhism',
        'Spirituality',
        'Islam',
        'Atheism',
        'Chiristianity',
        'Agnosticism',
        'Judaism',
        'Taoism',
        'Hinduism',
        'Buddhism',
    ]}
]

categories_ru = [
    {'Знания': [
        'Космос',
        'Философия',
        'Биология',
        'Будущее',
        'Физика',
        'Психология',
        'Образование',
        'История',
        'Математика',
        'Наука',
        'Covid-19'
    ]},
    {'Технологии': [
        'Product',
        'Стартапы',
        'Маркетинг',
        'AI',
        'SaaS',
        'Инженерия',
        'Crypto',
        'DTC',
        'Angel Investing',
        'Венчурный капитал',
        'VR/AR'
    ]},
    {'Язык': [
        'Русский',
        'Хинди',
        'Французский',
        'Арабский',
        'Португальский',
        'Японский',
        'Немецкий',
        'Испанский',
        'Мандаринский',
        'Индонезийский'
    ]},
    {'Образ жизни': [
        'Свадьба',
        'Путешествие',
        'Беременность',
        'Взросление',
        'Взаимоотношения',
        'Воспитание',
        'Знакомства',
        'Поддержка'
    ]},
    {'Благополучие': [
        'Веганство',
        'Здоровье',
        'Медитации',
        'На открытом воздухе',
        'Питание',
        'Психоделики',
        'Mindfulness',
        'Медицина',
        'Фитнес',
        'Вес'
    ]},
    {'Зависать с друзьями': [
        '¯\*(ツ)*/¯',
        'Chill vibes',
        'Коворкинг',
        'Late night',
        'Meet people',
        'Bring a Drink',
        'Welcome Newbies',
        'PTR'
    ]},
    {'Личность': [
        'Миллениалы',
        'Латиноамериканцы',
        'Женщины',
        'Цветные',
        'Черные',
        'Инвалиды',
        'Ген Z',
        'ЛГБТ',
        'Бэби-бумеры',
        'Ген X',
        'Южная Азия',
        'Восточная Азия',
        'Indiegenous'
    ]},
    {'Развлечения': [
        'Подкасты',
        'Выступления',
        'Музыка',
        'Сторителлинг',
        'Игры',
        'Комедия',
        'ТВ',
        'Караоке',
        'Мелочи',
        'Советы',
        'Эстрада',
        'Веселье',
        'Кино',
        'Звезды',
        'Аниме и манга'
    ]},
    {'Спорт': [
        'Гольф',
        'Soccer',
        'Езда на велосипеде',
        'Смешанные боевые искусства',
        'Крикет',
        'Теннис',
        'Формула 1',
        'Баскетбол',
        'Бейсбол',
        'Футбол'
    ]},
    {'Искусство': [
        'Фотография',
        'Красота',
        'Архитектура',
        'Литература',
        'Книги',
        'Art',
        'Реклама',
        'Еда и напитки',
        'Научная фантастика',
        'Дизайн',
        'Танцы',
        'Театр'
    ]},
    {'Hustle': [
        'Предпринимательство',
        'Недвижимость',
        'Инстаграм',
        'Сеть',
        'Малый бизнес',
        'Питч-практика',
        'Акции',
        'Клаб-хаус',
        'Тик-ток'
    ]},
    {'События в мире': [
        'Текущие события',
        'Социальные проблемы',
        'Геополитика',
        'Экономика',
        'Политика',
        'Рынки',
        'Климат'
    ]},
    {'Вера': [
        'Сикхизм',
        'Духовность',
        'Ислам',
        'Атеизм',
        'Христианство',
        'Агностицизм',
        'Иудаизм',
        'Таоизм',
        'Индуизм',
        'Буддизм',
    ]}
]
